# -*- coding: utf-8 -*-
"""loges.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JQl3i6HfOH39J33dtoVFpcT9IjZS510l
"""

stu=[["alice",85,90,95],["boob",75,80,82],["carol",92,88,91],["david",60,65,70]]
for i in stu:
  name=i[0]
  marks=i[1:]
  total=sum(marks)
  print(f"total marks of student {name}= {total}")

stu=[["alice",85,90,95],["boob",75,80,82],["carol",92,88,91],["david",60,65,70]]
for i in stu:
  name=i[0]
  marks=i[1:]
  total=sum(marks)
  average=total/(len(marks))
  higher_avg=0
  if average < higher_avg:
    higher_avg=average
  else:
    break
    stu_with_highest_avg=name
print(f"student with highest average: {name}- {average}")

stu=[["alice",85,90,95],["boob",75,80,82],["carol",92,88,91],["david",60,65,70]]
for i in stu:
  name=i[0]
  marks=i[1:]
  total=sum(marks)
  if total >250:
    print(f"total marks of student {name}= {total}")

stu=[["alice",85,90,95],["boob",75,80,82],["carol",92,88,91],["david",60,65,70]]
stu.append(["moni",99,76,54])
print(stu)

h=[["alice","reading","cycling"],["bob","drawing","football"],["carol","reading","swimming"],["david","cycling","gaming"]]
unique_h=set()
for i in h:
  name=i[0]
  hobby=i[1:]
  unique_h.update(hobby)
for hobby in unique_h:
  print(hobby)

h = [["alice", "reading", "cycling"],["bob", "drawing", "football"],["carol", "reading", "swimming"],["david", "cycling", "gaming"]]
unique_h = []
for i in h:
    name = i[0]
    hobbies = i[1:]
    for hobby in hobbies:
        if hobby not in unique_h:
            unique_h.append(hobby)
for hobby in unique_h:
    print(hobby)

h=[["alice","reading","cycling"],["bob","drawing","football"],["carol","reading","swimming"],["david","cycling","gaming"]]
a=[]
for i in h:
  name=i[0]
  hobby=i[1:]
  if "reading" in hobby:
    a.append(name)
print(len(a))

h=[["alice","reading","cycling"],["bob","drawing","football"],["carol","reading","swimming"],["david","cycling","gaming"]]
for i in h:
  name=i[0]
  hobby=i[1:]
  for j in i:
    if (j=="reading") or (j=="cycling"):
      print(name)

h=[["alice","reading","cycling"],["bob","drawing","football"],["carol","reading","swimming"],["david","cycling","gaming"]]
dict_h={}
for i in h:
  name=i[0]
  hobby=i[1:]
  dict_h[name]=hobby
print(dict_h)

sales=[["rice",120,130,125],["wheat",100,90,95],["oil",80,85,90],["sugar",110,115,105]]
for i in sales:
  name=i[0]
  s=i[1:]
  ss=sum(i[1:])
  print(f"total sales of {name}={ss}")

sales=[["rice",120,130,125],["wheat",100,90,95],["oil",80,85,90],["sugar",110,115,105]]
max_s=0
name=" "
for i in sales:
  m_s=i[3]
  if m_s>max_s:
    max_s=m_s
    name=i[0]
print(f"product with highest sales in march : {name} {max_s}")

sales=[["rice",120,130,125],["wheat",100,90,95],["oil",80,85,90],["sugar",110,115,105]]
t_j_s=0
t_f_s=0
t_m_s=0
for i in sales:
  j_s=i[1]
  f_s=i[2]
  m_s=i[3]
  t_j_s += j_s
  t_f_s += f_s
  t_m_s += m_s
print(f"sales in jan:{t_j_s}")
print(f"sales in feb:{t_f_s}")
print(f"sales in mar:{t_m_s}")

sales=[["rice",120,130,125],["wheat",100,90,95],["oil",80,85,90],["sugar",110,115,105]]
dict_sales={}
for i in sales:
  name=i[0]
  s=i[1:]
  dict_sales[name]=s
print(dict_sales)

books=[["wings of fire","a.p.j.abdul kalam","biography"],["1984","george orwell","fiction"],["the alchemist","paulocoelho","fiction"],["zero to one","peter theil","business"]]
for i in books:
  name=i[0]
  genre=i[2]
  if (genre=="fiction"):
    print(name)

books=[["wings_of_fire","kalam","biography"],["1984","george_orwell","fiction"],["the_alchemist","paulocoelho","fiction"],["zero_to_one","peter_theil","business"]]
unique_b=set()
for i in books:
  aut=i[1]
  unique_b.add(aut)
for aut in unique_b:
  print(aut)

books=[["wings of fire","a.p.j.abdul kalam","biography"],["1984","george orwell","fiction"],["the alchemist","paulocoelho","fiction"],["zero to one","peter theil","business"]]
a=[]
b=[]
c=[]
for i in books:
  genre=i[2]
  if genre=="biography":
    a.append(genre)
  if genre=="fiction":
    b.append(genre)
  if genre=="business":
    c.append(genre)
print(f"books in biography={len(a)}")
print(f"books in fiction={len(b)}")
print(f"books in business={len(c)}")

books=[["wings of fire","a.p.j.abdul kalam","biography"],["1984","george orwell","fiction"],["the alchemist","paulocoelho","fiction"],["zero to one","peter theil","business"]]
dict_books={}
for i in books:
  name=i[0]
  aut=i[1]
  genre=i[2]
  dict_books['title']=name
  dict_books['aut']=aut
  dict_books['genre']=genre
  print(dict_books)

import numpy as np
a=[1,2,3]
b=np.average(a)
print(b)

def avg(x):
  a=sum(x)/len(x)
  return(a)
l=[1,2,3]
a1=avg(l)
print(a1)

emp=[["arun","python","sql","excel"],["divya","tableau","python","power bi"],["rahul","excel","communication","sql"],["meena","python","ml","dl"]]
for i in emp:
  name=i[0]
  skills=i[1:]
  if ('python' in skills):
    print(f"name of employees skilled with python are {name}")

emp=[["arun","python","sql","excel"],["divya","tableau","python","power bi"],["rahul","excel","communication","sql"],["meena","python","ml","dl"]]
skill_count={}
for i in emp:
  skills=i[1:]
  for skill in skills:
    if skill in skill_count:
      skill_count[skill]+=1
    else:
      skill_count[skill]=1
for skill,count in skill_count.items():
  print(f"{skill} : {count}")

emp=[["arun","python","sql","excel"],["divya","tableau","python","power bi"],["rahul","excel","communication","sql"],["meena","python","ml","dl"]]
dict_emp={}
for i in emp:
  name=i[0]
  skills=i[1:]
  if 'python' in skills:
    dict_emp['python']=[name]
  if 'sql' in skills:
    dict_emp['sql']=[name]
  dict_emp[skills]=[name]
print(dict_emp)

emp=[["arun","python","sql","excel"],["divya","tableau","python","power bi"],["rahul","excel","communication","sql"],["meena","python","ml","dl"]]
for i in emp:
  name=i[0]
  skills=i[1:]
  if ('python' in skills) and ('sql' in skills):
    if('excel' in skills):
      print(name)

p=[["p101","arun",1200,"booked"],["p102","divya",1500,"available"],["p103","meena",1000,"booked"],["p104","none",1300,"available"]]
a=[]
for i in p:
  name=i[1]
  sts=i[3]
  if (sts=="booked"):
    a.append(name)
print(len(a))

p=[["p101","arun",1200,"booked"],["p102","divya",1500,"available"],["p103","meena",1000,"booked"],["p104","none",1300,"available"]]
for i in p:
  name=i[1]
  sts=i[3]
  if (sts=="available"):
    print(name)

p=[["p101","arun",1200,"booked"],["p102","divya",1500,"available"],["p103","meena",1000,"booked"],["p104","none",1300,"available"]]
for i in p:
  name=i[1]
  id=i[0]
  sts=i[3]
  if (sts=="booked"):
    print(name,id)

p=[["p101","arun",1200,"booked"],["p102","divya",1500,"available"],["p103","meena",1000,"booked"],["p104","none",1300,"available"]]
p.append(["p105","moni",2000,"booked"])
print(p)

pymnt=[["arun",6000000,3000000,3000000],["divya",750000,750000,0],["meena",5000000,1000000,4000000],["kumar",9000000,6000000,3000000]]
for i in pymnt:
  name=i[0]
  due=i[3]
  if (due>0):
    print(name)

def p(x):
  tot=x[1]
  paid=x[2]
  percent=(paid/tot)*100
  return (percent)
pymnt=[["arun",6000000,3000000,3000000],["divya",750000,750000,0],["meena",5000000,1000000,4000000],["kumar",9000000,6000000,3000000]]
for i in pymnt:
  name=i[0]
  percent= p(i)
  print(f"{name} has paid {percent: .2f}% of total amount")

pymnt=[["arun",6000000,3000000,3000000],["divya",750000,750000,0],["meena",5000000,1000000,4000000],["kumar",9000000,6000000,3000000]]
for i in pymnt:
  name=i[0]
  due=i[3]
  if (due==0):
    print(name)

p_info=[["p101","north layout","east"],["p102","north layout","west"],["p103","south layout","north"],["p104","east layout","east"]]
for i in p_info:
  loc=i[1]
  id=i[0]
  if (loc=="north layout"):
    print(id)

p_info=[["p101","north layout","east"],["p102","north layout","west"],["p103","south layout","north"],["p104","east layout","east"]]
a=[]
for i in p_info:
  id=i[0]
  dir=i[2]
  if (dir=="east"):
    a.append(id)
print(len(a))

p_info=[["p101","north layout","east"],["p102","north layout","west"],["p103","south layout","north"],["p104","east layout","east"]]
for i in p_info:
  id=i[0]
  loc=i[1]
  dir=i[2]
  p_id=input("enter the id : ")
  if (p_id==id):
    print(id , loc , dir)